# This is a basic workflow to help you get started with Actions

name: NPM publish

# Controls when the action will run. 
on:
  push:
    branches:
      - master
    
jobs:
  test:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: sudo npm install
      - run: sudo npm test

  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 10
  #     - uses: JS-DevTools/npm-publish@v1
  #       with:
  #         token: ${{ secrets.NPM_TOKEN }}
  #         package: ./src/package.json
          
