# This is a basic workflow to help you get started with Actions

name: NPM publish
on:
  push:
    branches:
      - master
    
jobs:
  test:
      runs-on: ubuntu-18.04
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 10
      - run: cd src && npm install
      - run: cd src && npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./src/package.json
          
